image: pytorch/pytorch:1.6.0-cuda10.1-cudnn7-runtime

stages:
  - deploy

before_script:
  - pip install sphinx sphinx_rtd_theme pytest coverage nibabel

pages:
  stage: deploy
  script:
  - sphinx-build docs/source docs/build
  - mv docs/build public/
  artifacts:
    paths:
    - public
  only:
  - master
